[program]
name = "analysis_test"

[analyzers.TestAnalyzer]
implementation = "TestAnalyzer"
config = { value = 5 }

[analyzers.TestOffsetAnalyzer]
implementation = "TestOffsetAnalyzer"
dependencies = ["TestAnalyzer"]
config = { "offset" = 4 }
